### ISSUE TITLE
let a user know when auth is bad

### ISSUE THREAD

**Issue by alfredodeza** [alfredodeza/helga-jenkins#12]
Instead of the current default which is to do nothing.

A way to do this could be to actually make a request, like `conn.get_info()` when constructing the credentials.

**Comment by ktdreyer** [comment]
This came up again today in a slightly different context: a user tried a `!ci` command without any token at all. Helga should say some warning in both scenarios.

**Comment by ktdreyer** [comment]
Newest versions of python-jenkins include a `get_whoami()` method that can be used for checking auth: http://python-jenkins.readthedocs.io/en/latest/api.html#jenkins.Jenkins.get_whoami

**Comment by alfredodeza** [comment]
The plugin was already going a `conn.get_info()` but wasn't catching the exception. It will now catch it and report nicely back to IRC.

Fixed with 7ed0572eb563ee36fcfa0f436b0473fe56364a11
